// <auto-generated />
namespace Proyectores.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dpto_validaciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dpto_validaciones));
        
        string IMigrationMetadata.Id
        {
            get { return "201802230023294_dpto_validaciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
