// <auto-generated />
namespace Proyectores.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_marcas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_marcas));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101534063_edit_marcas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
