// <auto-generated />
namespace Proyectores.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingdataanotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingdataanotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201802070137410_adding-data-anotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
