// <auto-generated />
namespace Proyectores.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201802101901524_marcas_edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201802101901524_marcas_edit));
        
        string IMigrationMetadata.Id
        {
            get { return "201802102049080_201802101901524_marcas_edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
